sudo: required
language: ruby

services:
  - docker
 
before_install:
- docker stop gruyere || true
- chmod +x ./scripts/travis-config.sh
- docker pull karthequian/gruyere:latest
- docker pull gauntlt/gauntlt
- docker run --rm -d -p 8008:8008 --name gruyere karthequian/gruyere:latest
- docker ps -a
- ./scripts/travis-config.sh

script:
  - cat ./config/cucumber.yml
  - docker run -t --rm -v $(pwd):/working -w /working gauntlt/gauntlt ./Tests/xss.attack --format=html > out.html
  - cat out.html
